agent_prompt: "Use tools to retrieve all information needed. Be creative and polite with marketing email."
llm_endpoint: "databricks-meta-llama-3-3-70b-instruct"
warehouse_id: 42b73f0557aae1e4
uc_functions:
  - "marion_test.email.*"